### PR TITLE
Add ability to load exisiting canvas data to SignaturePad

### PR DESCRIPTION
**Pull request by ultrox**
This is very usifull if you have multiple steps and want to edit/change
existing signuture.

### CODE REVIEW

**Comment by michaeldzjap** [comment]
I have to think about if I want to merge this to be honest. I don't see the immediate benefit. I suppose your suggestion is slightly more convenient than having to do it in two steps:
```javascript
<SignaturePad redrawOnResize={true} ref={ref => this.signaturePad = ref} />
...
this.signaturePad.fromDataURL(someBase64String);
```
or even
```javascript
<SignaturePad redrawOnResize={true} ref={ref => {
    this.signaturePad = ref;
    this.signaturePad.fromDataURL(someBase64String);
}} />
```
as you would have to do currently, but I'm not totally convinced this is a must have functionality.

Also, you'd have to add `this.props.value` to the prop types of the `SignaturePad` component and probably also add a `componentWillReceiveProps()` lifecycle method in case `this.props.value` gets updated so you can refresh the signature pad data in response (although this might be debatable).

**Comment by ultrox** [comment]
Hey Michael, 

I tryed both of those suggested methods and neather one worked when I used  it with functional component, that's why I propose this solution.

**Comment by ultrox** [comment]
Thats really strange, and not in the same time. 

I'm using latest react 16. I think it matter more how I use it.

I'm using signuture pad as custom wiget I build for https://github.com/mozilla-services/react-jsonschema-form. And also I dint' use redrawOnResize prop when I was testing, as I was using width,height fixed props.

**Comment by michaeldzjap** [comment]
Not specifying `redrawOnResize()` doesn't make a difference for me. Signature is loaded properly in the canvas when using a functional component. So yes, it is more likely that it is related to your specific use case.

**Comment by ultrox** [comment]
@michaeldzjap thanks man for your help!

**Pull request closed without merging**
